### PR TITLE
Documentation, more uniform methods

### PR DESCRIPTION
**Pull request by yenbekbay**

### CODE REVIEW

**Comment by mixdesign** [comment]
Thank you @yenbekbay.
Did you make sure example project compiles fine?

There is an error in NSLayoutConstraint+ConcisePureLayout.h file, due to `#import <Foundation/Foundation.h>`, changing it to `#import <UIKit/UIKit.h>` resolves the problem.

**Comment by yenbekbay** [comment]
@mixdesign Exactly. I fixed that error. The example project compiles fine for me.

**Comment by mixdesign** [comment]
@yenbekbay so, where is fix PR?

**Comment by yenbekbay** [comment]
@mixdesign What do you mean? It's included. Check the commits

**Pull request merged**
